"""Add internal_user column

Revision ID: 0496677c59f8
Revises: 39ed852bd9f3
Create Date: 2026-07-31 18:14:20.295642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0496677c59f8'
down_revision: Union[str, Sequence[str], None] = '39ed852bd9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('internal_user', sa.Integer(), nullable=True))
    
    # Safe data migration: Ensure existing users default to internal (1)
    # This prevents production bugs where old users would have NULL and be filtered out.
    op.execute("UPDATE users SET internal_user = 1 WHERE internal_user IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'internal_user')
    # ### end Alembic commands ###
