"""add lead metadata columns to tasks table

Revision ID: 0b3b60eff1e1
Revises: 5a7264d55848
Create Date: 2026-07-23 18:47:26.675500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3b60eff1e1'
down_revision: Union[str, Sequence[str], None] = '5a7264d55848'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('lead_source', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('lead_temperature', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('lead_score', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('deal_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('tasks', sa.Column('deal_probability', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('last_contact_date', sa.Date(), nullable=True))
    op.add_column('tasks', sa.Column('next_followup_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'next_followup_date')
    op.drop_column('tasks', 'last_contact_date')
    op.drop_column('tasks', 'deal_probability')
    op.drop_column('tasks', 'deal_value')
    op.drop_column('tasks', 'lead_score')
    op.drop_column('tasks', 'lead_temperature')
    op.drop_column('tasks', 'lead_source')
    # ### end Alembic commands ###
