"""add template_id to projects

Revision ID: 5a7264d55848
Revises: fcbcbbd914c6
Create Date: 2026-07-23 17:54:50.622372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7264d55848'
down_revision: Union[str, Sequence[str], None] = 'fcbcbbd914c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('template_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_projects_template_id'), 'projects', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_template_id'), table_name='projects')
    op.drop_column('projects', 'template_id')
    # ### end Alembic commands ###
