"""add template statuses table

Revision ID: fcbcbbd914c6
Revises: dc871046c84f
Create Date: 2026-07-23 08:23:49.944650

"""
"""add template statuses table

Revision ID: fcbcbbd914c6
Revises: dc871046c84f
Create Date: 2026-07-23 08:23:49.944650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbcbbd914c6'
down_revision: Union[str, Sequence[str], None] = 'dc871046c84f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    workflow_group_enum = postgresql.ENUM('OPEN', 'IN_PROGRESS', 'ON_HOLD', 'CLOSED', name='workflow_group_enum', create_type=False)

    template_statuses_table = op.create_table('template_statuses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_key', workflow_group_enum, nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_statuses_template_id'), 'template_statuses', ['template_id'], unique=False)
    op.add_column('workflow_statuses', sa.Column('template_status_id', sa.String(), nullable=True))
    op.create_foreign_key('fk_workflow_statuses_template_status_id', 'workflow_statuses', 'template_statuses', ['template_status_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # --- Data Seeding ---
    import uuid
    from datetime import datetime, timezone
    
    now = datetime.now(timezone.utc)
    
    # Generate deterministic UUIDs for these base statuses if we ever needed them, or just let uuid4 do it.
    # Using deterministic namespace just to be clean, but uuid4 is fine too.
    NAMESPACE_TEMPLATE = uuid.UUID('00000000-0000-0000-0000-000000000000') # Not strictly needed, we can just generate new ones
    
    blank_statuses = [
        {"id": str(uuid.uuid4()), "template_id": "tpl-blank", "name": "Open",         "group_key": "OPEN",        "color": "#6B7280", "position": 0, "is_default": True, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-blank", "name": "In Progress",  "group_key": "IN_PROGRESS", "color": "#7B68EE", "position": 0, "is_default": False, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-blank", "name": "On Hold",      "group_key": "ON_HOLD",     "color": "#F59E0B", "position": 0, "is_default": False, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-blank", "name": "Closed",       "group_key": "CLOSED",      "color": "#22C55E", "position": 0, "is_default": False, "created_at": now, "updated_at": now},
    ]
    
    lead_statuses = [
        {"id": str(uuid.uuid4()), "template_id": "tpl-lead", "name": "Not Started", "group_key": "OPEN", "color": "#94A3B8", "position": 0, "is_default": True, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-lead", "name": "Planning", "group_key": "OPEN", "color": "#FBBF24", "position": 1, "is_default": False, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-lead", "name": "In Progress", "group_key": "IN_PROGRESS", "color": "#3B82F6", "position": 0, "is_default": False, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-lead", "name": "Waiting on Client", "group_key": "ON_HOLD", "color": "#F59E0B", "position": 0, "is_default": False, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-lead", "name": "Internal Review", "group_key": "IN_PROGRESS", "color": "#8B5CF6", "position": 1, "is_default": False, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-lead", "name": "Client Review", "group_key": "IN_PROGRESS", "color": "#D946EF", "position": 2, "is_default": False, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-lead", "name": "Changes Requested", "group_key": "ON_HOLD", "color": "#F43F5E", "position": 1, "is_default": False, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-lead", "name": "Completed", "group_key": "CLOSED", "color": "#22C55E", "position": 0, "is_default": False, "created_at": now, "updated_at": now},
        {"id": str(uuid.uuid4()), "template_id": "tpl-lead", "name": "Cancelled", "group_key": "CLOSED", "color": "#EF4444", "position": 1, "is_default": False, "created_at": now, "updated_at": now},
    ]
    
    op.bulk_insert(template_statuses_table, blank_statuses + lead_statuses)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_workflow_statuses_template_status_id', 'workflow_statuses', type_='foreignkey')
    op.drop_column('workflow_statuses', 'template_status_id')
    op.drop_index(op.f('ix_template_statuses_template_id'), table_name='template_statuses')
    op.drop_table('template_statuses')
    # ### end Alembic commands ###
